CREATE DATABASE IF NOT EXISTS user_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE user_db;

CREATE TABLE IF NOT EXISTS user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    phone VARCHAR(11) NOT NULL UNIQUE COMMENT '手机号，用于登录',
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL UNIQUE COMMENT '昵称，全局唯一',
    avatar VARCHAR(255) DEFAULT '',
    email VARCHAR(100) DEFAULT '',
    bio VARCHAR(500) DEFAULT '',
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '1正常 0封禁',
    banned_until DATETIME DEFAULT NULL COMMENT '封禁截止时间，NULL表示永久',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
