USE user_db;
SET NAMES utf8mb4;

ALTER TABLE user
    ADD COLUMN gender VARCHAR(10) DEFAULT 'SECRET' COMMENT 'MALE/FEMALE/SECRET' AFTER bio,
    ADD COLUMN birth_month DATE DEFAULT NULL COMMENT '出生日期' AFTER gender;
